print("=================")
print("Esto es un")
print("ejemplo")
print("=================")
print("Esto es el", end=" ")
print("Resultado")
print("=================")
print("1","2","3","4","5","6")
print("=================")
print("1","2","3","4","5","6", sep=",")
print("=================")