print("Ejemplo de uso de count")
print("=====================================")
text="mi mamá me mima"
print(text)
print()
print("Cantidad de veces que aparece 'm'= ", text.count("m"))
print()
print("Cantidad de veces que aparece 'ma'= ",text.count("ma"))
print()
print("Cantidad de veces que aparece 'm' desde la posición 5= ", text.count("m", 5))
print()
print("Cantidad de veces que aparece 'm' desde la posición 5 hasta la 10= ", text.count("m", 5, 10))
print()
print("Cantidad de veces que aparece  'm' desdes la posicion -4 a -1= ", text.count("m",-4, -1))

print()
print("=====================================")
print("Ejemplo usando endswith")
print(text)
print("Termina con 'mima'? ", text.endswith("mima"))
print()
print("Termina con a? ",text.endswith("a"))
print()
print("Termina con 'mima' desde la posición 5? ", text.endswith("mima", 5))
print()
print("Termina con 'mima' desde la posición 5 hasta la 10? ", text.endswith("mima", 5, 10))

print()
print("=====================================")
print("Ejemplo usando startswith")
print(text)
print()
print("Comienza con 'a'? ",text.startswith("a"))
print()
print("Comienza con 'm'? ", text.startswith("m"))
print()
print("Comienza con 'mi' desde la posición 2? ", text.startswith("mi", 2))
print()
print("Comienza con 'mi' desde la posición 0 hasta la 5? ", text.startswith("mi", 0, 5))
print()

