print("Ejemplo de uso de substring")
print("=====================================")
print()
text="0123456789"
print("Texto original: ", text)
print()
print("Subcadena desde la posición 2 hasta la 5: ", text[2:5])
print()
print("Subcadena desde la posición 2 hasta el final: ", text[2:])
print()
print("Subcadena desde el inicio hasta la posición 5: ", text[:5])
print()
print("Subcadena desde la posición 2 hasta la 5 con paso 2: ", text[2:5:2])
print()
print("Subcadena desde el inicio hasta el final con paso 2: ", text[::2])
print()
print("Subcadena desde el final hasta el inicio: ", text[::-1])
print()