print("=====================================")
t2="El vIAje A la PlAya es MUy GraTIFicanTe ParA mI"
print(t2)
print()
print("Texto aplicanco capitalize: ")
print(t2.capitalize())
print()
print("Texto aplicanco title: ")
print(t2.title())
print()
print("Texto aplicanco swapcase: ")
print(t2.swapcase())
print()
print("Texto aplicanco upper: ")
print(t2.upper())
print()
print("Texto aplicanco lower: ")
print(t2.lower())
print()

print("=====================================")
print("Texto aplicanco center: ")
print(t2.center(100, "*"))
print()
print("Texto aplicanco ljust: ")
print(t2.ljust(100, "-"))
print()
print("Texto aplicanco rjust sin simbolo: ")
print(t2.rjust(100))
print()
